# Generated by Django 6.0.3 on 2026-03-18 03:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('templates_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('doc_id', models.CharField(help_text='Human-readable ID, e.g. DOC-2026-001', max_length=20, unique=True, verbose_name='Document ID')),
                ('title', models.CharField(max_length=512)),
                ('category', models.CharField(default='GST', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('issued', 'Issued'), ('signed', 'Signed'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('template_name', models.CharField(blank=True, default='', max_length=128)),
                ('editor_mode', models.CharField(choices=[('structured', 'Structured'), ('canvas', 'Canvas')], default='structured', max_length=16)),
                ('canvas_data', models.JSONField(blank=True, default=dict, help_text='JSON blob matching TemplateCanvasData from frontend', verbose_name='Canvas Data')),
                ('structure', models.JSONField(blank=True, default=list, help_text='JSON array matching StructureNode[] from frontend', verbose_name='Structure Tree')),
                ('enabled_blocks', models.JSONField(blank=True, default=dict, help_text='Record<string, boolean> — addon block toggle state', verbose_name='Enabled Blocks')),
                ('added_block_ids', models.JSONField(blank=True, default=list, help_text='Array of block IDs added via inspector recommendations', verbose_name='Added Block IDs')),
                ('project_name', models.CharField(blank=True, default='', max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('starred', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('sha256', models.CharField(blank=True, default='', max_length=64, verbose_name='SHA-256')),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, default='', max_length=512)),
                ('imported_from', models.CharField(blank=True, default='', help_text='Original file format: pdf, docx, xlsx, etc.', max_length=16)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='documents/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='templates_catalog.template')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('actor', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='documents.document')),
            ],
            options={
                'db_table': 'audit_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('indigo', 'Indigo'), ('emerald', 'Emerald'), ('amber', 'Amber'), ('rose', 'Rose'), ('violet', 'Violet'), ('cyan', 'Cyan'), ('gray', 'Gray')], default='indigo', max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.folder')),
            ],
            options={
                'db_table': 'folders',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.folder'),
        ),
        migrations.CreateModel(
            name='VersionEntry',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=16)),
                ('actor', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('canvas_data_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_history', to='documents.document')),
            ],
            options={
                'db_table': 'version_entries',
                'ordering': ['-version'],
                'unique_together': {('document', 'version')},
            },
        ),
    ]
