# Generated by Django 6.0.3 on 2026-03-18 03:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('GST', 'GST'), ('Business', 'Business'), ('Legal', 'Legal'), ('HR', 'HR'), ('Finance', 'Finance')], default='GST', max_length=32)),
                ('pack', models.CharField(blank=True, default='', max_length=64)),
                ('estimated_time', models.CharField(default='~3 min', max_length=32)),
                ('required_fields', models.PositiveIntegerField(default=0)),
                ('badges', models.JSONField(blank=True, default=list, help_text='e.g. ["GST","Rule 46"]')),
                ('version', models.CharField(default='1.0', max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('prepared_by', models.CharField(blank=True, default='', max_length=255)),
                ('prepared_for', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('default_structure', models.JSONField(blank=True, default=list, help_text='Default StructureNode[] tree for new documents of this template')),
                ('default_canvas_data', models.JSONField(blank=True, default=dict, help_text='Default TemplateCanvasData for new documents of this template')),
                ('default_validations', models.JSONField(blank=True, default=list, help_text='Default ValidationRule[] for this template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlockDefinition',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('canonical_id', models.CharField(help_text='Canonical ID in group.kebab-case format, e.g. billing.invoice-no', max_length=64)),
                ('group', models.CharField(max_length=32)),
                ('block_type', models.CharField(choices=[('header', 'Header'), ('field', 'Field'), ('table', 'Table'), ('summary', 'Summary'), ('signature', 'Signature'), ('section', 'Section')], max_length=16)),
                ('label', models.CharField(max_length=128)),
                ('locked', models.BooleanField(default=False, help_text='Locked blocks cannot be edited/removed by users')),
                ('default_enabled', models.BooleanField(default=True)),
                ('is_addon', models.BooleanField(default=False, help_text='Addon blocks can be toggled on/off in the inspector')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='templates_catalog.template')),
            ],
            options={
                'db_table': 'block_definitions',
                'ordering': ['group', 'canonical_id'],
                'unique_together': {('template', 'canonical_id')},
            },
        ),
    ]
