# Generated by Django 6.0.3 on 2026-03-18 03:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('role', models.CharField(choices=[('signer', 'Signer'), ('approver', 'Approver'), ('cc', 'CC')], default='signer', max_length=16)),
                ('methods_allowed', models.JSONField(default=list, help_text='e.g. ["otp_verified", "aadhaar_esign"]')),
                ('method_used', models.CharField(blank=True, choices=[('otp_verified', 'OTP Verified'), ('aadhaar_esign', 'Aadhaar eSign'), ('dsc', 'DSC')], default='', max_length=16)),
                ('status', models.CharField(choices=[('not_viewed', 'Not Viewed'), ('viewed', 'Viewed'), ('started', 'Started'), ('signed', 'Signed'), ('failed', 'Failed'), ('declined', 'Declined')], default='not_viewed', max_length=16)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('signature_hash', models.CharField(blank=True, default='', max_length=64)),
                ('color_code', models.CharField(default='#6366f1', max_length=7)),
            ],
            options={
                'db_table': 'signers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VerifyAttempt',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('uvc', models.CharField(max_length=20)),
                ('result', models.CharField(choices=[('valid', 'Valid'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('not_found', 'Not Found')], max_length=16)),
                ('ip_masked', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'verify_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureRecord',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('method_used', models.CharField(max_length=16)),
                ('signed_at', models.DateTimeField()),
                ('signature_hash', models.CharField(max_length=64)),
                ('ip_masked', models.CharField(max_length=32)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='signing.signer')),
            ],
            options={
                'db_table': 'signature_records',
                'ordering': ['-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='SignEvidence',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('cert_chain_ref', models.TextField(blank=True, default='')),
                ('ocsp_ref', models.TextField(blank=True, default='')),
                ('crl_ref', models.TextField(blank=True, default='')),
                ('tsa_ref', models.TextField(blank=True, default='')),
                ('signature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='signing.signaturerecord')),
            ],
            options={
                'db_table': 'sign_evidence',
            },
        ),
        migrations.CreateModel(
            name='SigningRequest',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('request_id', models.CharField(help_text='Human-readable ID, e.g. SGN-2026-001', max_length=20, unique=True)),
                ('doc_version_id', models.CharField(blank=True, default='', max_length=36)),
                ('category', models.CharField(choices=[('Legal', 'Legal'), ('HR', 'HR'), ('Finance', 'Finance'), ('Internal', 'Internal'), ('Vendor', 'Vendor'), ('Board', 'Board')], default='Finance', max_length=16)),
                ('status', models.CharField(choices=[('awaiting', 'Awaiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='awaiting', max_length=16)),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA-256')),
                ('display_fingerprint', models.CharField(blank=True, default='', max_length=20)),
                ('owner_email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, default='')),
                ('reminder_schedule', models.JSONField(blank=True, default=list, help_text='Array of hours, e.g. [24, 48, 72]')),
                ('delivery_channels', models.JSONField(blank=True, default=list, help_text='e.g. ["email"]')),
                ('uvc', models.CharField(blank=True, default='', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_requests', to='documents.document')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'signing_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignEvent',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('actor', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ip_masked', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signing_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='signing.signingrequest')),
            ],
            options={
                'db_table': 'sign_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='signer',
            name='signing_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='signing.signingrequest'),
        ),
        migrations.AddField(
            model_name='signaturerecord',
            name='signing_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_records', to='signing.signingrequest'),
        ),
        migrations.CreateModel(
            name='UvcCode',
            fields=[
                ('uvc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signing_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uvc_code', to='signing.signingrequest')),
            ],
            options={
                'db_table': 'uvc_codes',
            },
        ),
        migrations.CreateModel(
            name='SigningPolicy',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('doc_category', models.CharField(max_length=16)),
                ('allow_otp', models.BooleanField(default=True)),
                ('allow_esign', models.BooleanField(default=True)),
                ('allow_dsc', models.BooleanField(default=False)),
                ('link_expiry_days', models.PositiveIntegerField(default=7)),
                ('require_review_checkbox', models.BooleanField(default=True)),
                ('disable_partial_download', models.BooleanField(default=False)),
                ('evidence_auto_attach', models.BooleanField(default=True)),
                ('otp_sends_per_hour', models.PositiveIntegerField(default=5)),
                ('verify_attempts_per_hour_per_ip', models.PositiveIntegerField(default=10)),
                ('file_upload_max_size_mb', models.PositiveIntegerField(default=25)),
                ('audit_log_retention_days', models.PositiveIntegerField(default=2555)),
                ('signed_pdf_retention_days', models.PositiveIntegerField(default=2555)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_policies', to='accounts.organization')),
            ],
            options={
                'db_table': 'signing_policies',
                'unique_together': {('organization', 'doc_category')},
            },
        ),
    ]
